### PR TITLE
fix: npm change .gitignore to .npmignore

### LINKED ISSUE #30: npm init or npx will change .gitignore to .npmignore
image
image

And here is a relative issue about npm init https://github.com/npm/npm/issues/1862

### PR DESCRIPTION
**Pull request by lianghx-319**
## Test
image

CLOSE #30

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,52 +1,57 @@
...
+const fs = require("fs-extra");
+const argv = require("minimist")(process.argv.slice(2));
 
 async function init() {
-  const targetDir = argv._[0] || '.'
-  const cwd = process.cwd()
-  const root = path.join(cwd, targetDir)
-  console.log(`Scaffolding project in ${root}...`)
+  const targetDir = argv._[0] || ".";
+  const cwd = process.cwd();
```
Comment (underfin) [inline index.js]: Can you revert  double quotes and the semicolons of line end.

Comment (lianghx-319) [reply index.js]: Sorry, my editor auto-format code. Have recovered.

**Review by underfin — APPROVED** [review]
